apiVersion: apps/v1
kind: Deployment
metadata:
  name: segmentation-api
  namespace: segmentation-mlops
  labels:
    app: segmentation-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: segmentation-api
  template:
    metadata:
      labels:
        app: segmentation-api
    spec:
      containers:
        - name: api
          image: ghcr.io/elizavetakorkina2211-coder/customer_clusterisation_mlops_final:7f9f294074d7ec904e25451d7f56570bc6beff5a
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: MLFLOW_TRACKING_URI
              value: "http://mlflow.segmentation-mlops.svc.cluster.local:5000"
            - name: MLOPS_MLFLOW_TRACKING_URI
              value: "http://mlflow.segmentation-mlops.svc.cluster.local:5000"
            - name: MLOPS_ROOT
              value: "/app"
            - name: MLOPS_DB_PATH
              value: "/data/predictions.db"
          volumeMounts:
            - name: data-volume
              mountPath: /data
          readinessProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: segmentation-db-pvc
