apiVersion: v1
kind: Service
metadata:
  name: segmentation-api
  namespace: segmentation-mlops
spec:
  selector:
    app: segmentation-api
  ports:
    - port: 80
      targetPort: 8000
      name: http
  type: ClusterIP
